package sm.dao;

import org.apache.ibatis.annotations.Param;

import sm.pojo.NoveUser;

public interface NoveUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_user
     *
     * @mbggenerated
     */
    int insert(NoveUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_user
     *
     * @mbggenerated
     */
    int insertSelective(NoveUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_user
     *
     * @mbggenerated
     */
    NoveUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoveUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nove_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoveUser record);
    
    //登录用户
    NoveUser getRoleName(@Param("userName") String u);
  	//注册用户
    NoveUser getRoleMobile(@Param("userTel") String mobile);
    
    //重置密码
  	void updateRolePassword(NoveUser u);
}